# Tensor 생성
- 파이토치에서 데이터를 저장하는 자료구조
- ndarray와 성격, 사용법이 유사하다.

##  원하는 형태(shape) 텐서 생성
- **torch.tensor(자료구조 \[, dtype\])**
    - 지정한 dtype(Data type)에 맞는 Tensor객체를 생성해서 반환한다.
    - 
## 특정 타입의 Tensor를 직접 생성
- torch.tensor()로 생성하면서 dtype을 지정하면 아래 타입의 Tensor객체가 생성된다.
- 원하는 Type의 Tensor클래스를 이용해 직접 생성해도 된다.
- **torch.FloatTensor(자료구조)**
    - float32 타입 텐서 생성
- **torch.LongTensor(자료구조)** 
    - int64 타입 텐서생성
- 그외
    - BoolTensor(bool), CharTensor(int8), ShortTensor(int16), IntTensor(int32), DoubleTensor(float64)
    
## tensor 상태 조회
- **tensor.shape, tensor.size(\[축번호\])**
    -  tensor의 shape조회
- **tensor.dtype, tensor.type()**
    - tensor 원소들의 데이터타입 조회
    - dtype은 **data type**을 type()은 tensor **객체의 클래스 타입**을 반환한다.
- **tensor.ndim, tensor.dim()**  : tensor 차원
- **tensor.numel()**: 전체 원소 개수



In [1]:
import torch

torch.__version__

'2.1.0'

In [2]:
a = torch.tensor([[1,2],[3,4]], dtype=torch.float32)

print("shape:", a.shape, a.size())  # 전체 shape
print("축별 크기:", a.shape[0], a.size(0))  # 축별 size
print("type:", a.type(), a.dtype)  
print('차원크기:', a.dim(), a.ndim)
print('원소개수:', a.numel())
print("device:", a.device) 

shape: torch.Size([2, 2]) torch.Size([2, 2])
축별 크기: 2 2
type: torch.FloatTensor torch.float32
차원크기: 2 2
원소개수: 4
device: cpu


In [3]:
torch.tensor(range(10))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#Float, Double(32, 64bit 실수)/Int, Long(32, 64 bit 정수) type Tensor
b = torch.FloatTensor([1,3,7])  #float32
print(b.dtype)
c = torch.IntTensor([10,20,30]) # int64
print(c.dtype)
d = torch.DoubleTensor([1, 2, 3])  # torch.tensor([], dtype=torch.float64)
print(d.dtype)
e = torch.LongTensor([10, 20, 30, 40])  # torch.tensor([], dtype=torch.int64)
print(e.dtype)

torch.float32
torch.int32
torch.float64
torch.int64


## 특정 값으로 구성된 Tensor 생성
- **torch.zeros(\*size), zeros_like(텐서)**: 0으로 구성된 tensor 생성
- **torch.ones(\*size), ones_like(텐서)**: 1로 구성된 tensor생성
- **torch.full(\*size), full_like(텐서)**: 지정한 값으로 구성된 tensor생성
    

In [5]:
torch.zeros(3,2,3)  # 3 X 2 X 3: 3차원
torch.ones(2,3)  # 2 X 3: 2차원
torch.full((3,2), fill_value=100)  # 3 X 2: 2차원, 100으로 구성


tensor([[100, 100],
        [100, 100],
        [100, 100]])

In [6]:
a = torch.tensor([[1, 2],[3,4]])  # 2 X 2
print(a.shape)
b = torch.zeros_like(a)  # a와 동일한 shape의 tensor를 생성
b = torch.ones_like(a)
b = torch.full_like(a, 20)
b.shape

torch.Size([2, 2])


torch.Size([2, 2])

## 동일한 간격으로 떨어진 값들로 구성된 배열생성
- **torch.arange(start=0, end, step=1)** 
- **torch.linspace(start, end, steps,)** : steps - 원소개수

In [8]:
torch.arange(10)  # 0 ~ 10-1
torch.arange(0, 1, 0.1)  # 0 ~ 1, 증감: 0.1
torch.arange(10, 1, -1)  # 10 ~ 1+1, 증감: -1

tensor([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [10]:
torch.linspace(0, 10, 5)  # 0 ~ 10, 등분한값 5개
torch.linspace(0, 1, 11)  # 0 ~ 1, 등분한 값 11개

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])

## 빈 tensor 생성
- **torch.empty(\*size)**

In [20]:
torch.empty(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## 난수를 이용한 생성

- **torch.rand(\*size)**: 0 ~ 1사이 실수로 구성된 배열을 생성. 각 값은 균등분포를 따른다.
- **torch.randn(\*size)**: 표준정규분포(평균:0, 표준편차:1)를 따르는 실수로 구성된 배열 생성
- **torch.randint(low=0, high, size)**: 지정한 범위의 정수로 구성된 배열 생성
- **torch.randperm(n)**: 0 ~ n-1 사이의 정수를 랜덤하게 섞은 값을 원소로 가지는 배열 생성

In [24]:
torch.manual_seed(1004)  # seed 설정
torch.rand(100)
torch.randn(3,3)
torch.randint(1, 10, (3,3))  
torch.randperm(5)  # 0, 1, 2, 3, 4

tensor([1, 3, 0, 4, 2])

In [29]:
a = torch.arange(1, 10)
print(a)
# index를 섞어서 데이터를 섞음(shuffle)
idx = torch.randperm(9)
a[idx]

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([6, 2, 7, 5, 4, 1, 8, 9, 3])

## tensor를 상수로 변환
- tensor객체.item()
    - Scalar(상수) tensor를 python 상수로 변환

In [32]:
# tensor.item() -> torch.Tensor()객체 -> 파이썬 상수로 변환
a = torch.tensor(10)
print(a)
print(a.item())  # 파이썬 정수로 변환

tensor(10)
10


In [33]:
b = torch.tensor([20])
print(b)
print(b.item()) #원소가 하나인 배열 변환 가능

tensor([20])
20


In [34]:
c = torch.tensor([1, 10, 100])
print(c)
# print(c.item()) #원소가 여러개일 경우 Exception발생

tensor([  1,  10, 100])


In [35]:
# d = torch.tensor([10], device='cuda')  # device='cuda' => VRAM(GPU의 RAM)에 저장
d = torch.tensor([10], device='mps')  # 맥은 mps인가?
print(d)
print(d.item())

AssertionError: Torch not compiled with CUDA enabled

## ndarray 호환

- ndarray를 tensor로 생성
    - **torch.tensor(ndarray)**
    - **torch.from_numpy(ndarray)**
- tensor를 ndarray로 변환
    - **tensor.numpy()**
    - tensor가 gpu에 있을 경우 cpu로 옮긴 뒤 변환해야 한다.

In [36]:
import numpy as np
import torch

In [37]:
# ndarray -> tensor
arr = np.arange(1,10)

torch.tensor(arr)
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# tensor -> ndarray
t = torch.randn(3,3)
print(t)
t.numpy()

tensor([[-0.1761, -1.6682, -1.7317],
        [-0.5429, -0.5746,  1.1447],
        [-0.5256,  1.7993,  0.5378]])


array([[-0.17609052, -1.6682048 , -1.7316618 ],
       [-0.5429196 , -0.57457906,  1.1447077 ],
       [-0.5255575 ,  1.799259  ,  0.53779405]], dtype=float32)

In [ ]:
t2 = torch.randn(2,2, device="cuda")
t2

In [ ]:
# VRAM에 있는 Tensor객체는 ndarraㄹfy 변환이 안됨
## VRAM의 Tensorfmf RAM(CPI)오 이상시킨뒤의 벼놘
t2.numpy()
t2.to('cpu').numpy()  

## Tensor gpu/cpu 메모리로 옮기기

- pytorch는 데이터셋인 tensor를 cpu메모리와 gpu 메모리로 서로 옮길 수 있다.
    - 데이터에 대한 연산처리를 어디서 하느냐에 따라 메모리를 선택한다.
    - 장치는 문자열로 설정한다.
        - CPU 사용: "cpu"
        - nvida GPU: "cuda"
        - Apple m1: "mps"
            - pytorch 1.12 부터 지원
- 옮기기
    - tensor 생성시 `device` 파라미터를 이용해 설정
    - `tensor.to(device)`를 이용해 설정
- 현재 실행환경에서 어떤 장비를 사용할 수 있는지 확인
    - nvidia gpu 사용가능확인
        - `torch.cuda.is_available()` - nvida gpu 사용가능 여부
        - `torch.backends.mps.is_available()` - M1 사용가능 여부

In [43]:
device = 'mps' if torch.backends.mps.is_available() else 'cpu'  # 맥
# device = 'cuda' if torch.cuda.is_available() else 'cpu'       # 윈도우
device

'mps'

In [44]:
t = torch.tensor([1, 2, 3], dtype=torch.float32, device=device)
t

# t2 = t.to("cpu")
# t2

tensor([1., 2., 3.], device='mps:0')

# 원소 조회및 변경 - indexing/slicing

- 대부분 Numpy 와 동일
    - **slicing에서 step을 <u>음수로 지정할 수 없다.</u>**


In [53]:
t = torch.randint(-10, 10, (100, ))
t

tensor([  1,   9,   5,  -9,  -1,   9,  -1,  -8,   5,   2,   3,  -2,  -3,  -6,
         -8,   1,   0,   1,  -5,  -3, -10,   7,  -6,  -5,  -4,  -3,   2,  -7,
          1,   4,   0,   4,  -4, -10,   9,   7,   6,  -6,  -9,   7,  -6,  -6,
         -4,   2,  -6,   6,   9,   0,  -1,  -6,   1,  -2,  -9,   4,   9,  -6,
          2,  -4,   1,   9,   2,  -2,   4,  -1,   8,   1,  -9,  -3,  -1,  -6,
         -6,  -9,  -9,   7,   7,  -6,   3,   8,   3,  -1,  -5,  -4,  -1,   9,
         -4,   0,  -1,   9,  -3,   7,  -8,   4,  -7,   5,  -9,  -1,   7,   4,
          5,   9])

In [54]:
t[0], t[[1, 5, -1]]

(tensor(1), tensor([9, 9, 9]))

In [55]:
t[:5]
t[10:15]
t[90:]
t[3:30:3]
# t[10:1:-2]  #에러
t[1:10:2].flip(dims=(0,)) #reverse

tensor([ 2, -8,  9, -9,  9])

In [56]:
# boolean index
t[t > 0]  # 0보다 큰 값들만 조회

tensor([1, 9, 5, 9, 5, 2, 3, 1, 1, 7, 2, 1, 4, 4, 9, 7, 6, 7, 2, 6, 9, 1, 4, 9,
        2, 1, 9, 2, 4, 8, 1, 7, 7, 3, 8, 3, 9, 9, 7, 4, 5, 7, 4, 5, 9])

In [57]:
# 변경
t[0] = 100
t

tensor([100,   9,   5,  -9,  -1,   9,  -1,  -8,   5,   2,   3,  -2,  -3,  -6,
         -8,   1,   0,   1,  -5,  -3, -10,   7,  -6,  -5,  -4,  -3,   2,  -7,
          1,   4,   0,   4,  -4, -10,   9,   7,   6,  -6,  -9,   7,  -6,  -6,
         -4,   2,  -6,   6,   9,   0,  -1,  -6,   1,  -2,  -9,   4,   9,  -6,
          2,  -4,   1,   9,   2,  -2,   4,  -1,   8,   1,  -9,  -3,  -1,  -6,
         -6,  -9,  -9,   7,   7,  -6,   3,   8,   3,  -1,  -5,  -4,  -1,   9,
         -4,   0,  -1,   9,  -3,   7,  -8,   4,  -7,   5,  -9,  -1,   7,   4,
          5,   9])

In [59]:
t = torch.arange(1, 10).reshape(3,3)  # 2차원: index - 2방향
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [64]:
# t[0축, 1축]
t[0]
t[0, 0]
t[1, 1]
t[0, 1]

tensor(2)

In [65]:
t[[1,0], [2,2]]  #(1,2), (0,2)
# t[[첫번째 값, 두번쨰값]-0축, [첫번째값, 두번째값]-1축]

tensor([6, 3])

# Reshape

## shape 변경
- tensor객체.reshape(\*shape) / view(\*shape) 이용
    - 변환 후 값을 변경하면 원본 배열의 값도 같이 바뀐다.
 > tensor.clone(): tensor를 복제한다.

In [66]:
a=torch.rand(12)  # (12, )
a2 = a.reshape(3,4)  # 3 X 4
a3 = a.reshape((3,2,2))  # 3 X 2 X 2
a4 = a.reshape((3,2,-1))  # 3 X 2 X 2  #한 개 axis는 -1로 설정가능하고 그럼 계산해서 알아서 설정해 준다.
print(a.shape, a2.size(), a3.shape, a4.shape)

torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [67]:
a5 = a.view(3,4)
a6 = a.view((3,2,2))
a7 = a.view((3,2,-1))  #한개 axis는 -1로 설정가능
print(a.shape, a5.size(), a6.shape, a7.shape)

torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [68]:
a5[0, 0] = 12.1
a2[0, 1] = 15.1

print(a)

tensor([12.1000, 15.1000,  0.6514,  0.0986,  0.8461,  0.1435,  0.1996,  0.3179,
         0.5149,  0.3906,  0.0410,  0.0151])


In [69]:
# tensor복사: clone() 메소드
r = a.clone().reshape(3,4)
r[0,0] = 100.1
print(a)

tensor([12.1000, 15.1000,  0.6514,  0.0986,  0.8461,  0.1435,  0.1996,  0.3179,
         0.5149,  0.3906,  0.0410,  0.0151])


In [70]:
r

tensor([[1.0010e+02, 1.5100e+01, 6.5143e-01, 9.8564e-02],
        [8.4610e-01, 1.4353e-01, 1.9963e-01, 3.1790e-01],
        [5.1488e-01, 3.9056e-01, 4.0980e-02, 1.5105e-02]])

## dummy 축 늘리기

- None을 이용 (numpy의 newaxis 대신 None을 사용한다.)
- unsqueeze(dim=축번호)

In [74]:
import torch
a = torch.tensor([[10,20],[10,20]])
print(a.shape)

a1, a2 = a[None, :], a.unsqueeze(dim=0)
print(a1.shape, a2.shape)

a3, a4 = a[:, :, None], a.unsqueeze(dim=-1) 
print(a3.shape, a4.shape)

a5, a6 = a3[:,None,:,:], a3.unsqueeze(dim=1)
print(a5.shape, a6.shape)

torch.Size([2, 2])
torch.Size([1, 2, 2]) torch.Size([1, 2, 2])
torch.Size([2, 2, 1]) torch.Size([2, 2, 1])
torch.Size([2, 1, 2, 1]) torch.Size([2, 1, 2, 1])


## dummy 축 제거
- squeeze(\[dim=축번호\]) 이용

In [76]:
t = torch.rand(3, 1, 3, 1)
print(t.shape)

r1 = t.squeeze()  # 축을 명시 하지 않으면 모두 제거
print(r1.shape)

r2 = t.squeeze(dim=1) # 특정 axis 제거
print(r2.shape)

r3 = t.squeeze(dim=[1,3]) # 여러 axis의 dummy 축 제거
print(r3.shape)

torch.Size([3, 1, 3, 1])
torch.Size([3, 3])
torch.Size([3, 3, 1])
torch.Size([3, 3])


## tensor 합치기
torch.cat([tensorA, tensorB, ...], dim=0)

In [77]:
a = torch.arange(10).reshape(2,5)  # 0 ~ 9
b = torch.arange(10,20).reshape(2,5)  # 10 ~ 19 
c = torch.arange(20,30).reshape(2,5)  # 20 ~ 29
d = torch.arange(10,19).reshape(3,3)  # 10 ~ 18
print(a)
print(b)
print(c)
print(d)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])


In [78]:
torch.cat([a, b], dim=0)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [79]:
torch.cat([a, b, c], dim=0)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])

In [80]:
torch.cat([a, b], axis=1) # dim 대신 axis사용가능

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [81]:
torch.cat([a, b, c], axis=1)

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19, 25, 26, 27, 28, 29]])

In [82]:
torch.cat([a, b], axis=-1)  # 음수: 뒤에서부터. -1: 마지막축

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [85]:
# 합치려는 기준 축이외의 축 size는 같아야 함
# torch.cat([a, d])  #Error - (2, 5) 와 (3, 3) 기준: 0축(기본)

## 값의 위치(index) 변경
- tensor 원소의 축별 index의 위치를 바꾼다.
- `tensor.transpose(axis1, axis2)` 
    - 두 축의 자리만 변경 할 수 있다.
- `tensor.permute(axis1, axis2, axis3, ..)`
    - 두 개 이상의 축 자리를 변경한다.

In [86]:
a = torch.arange(12).reshape(4, 3)
b = a.transpose(1, 0)  # index의 1축을 0축으로, 0축을 1축으로 바꾼다
print(a.shape, b.shape)

torch.Size([4, 3]) torch.Size([3, 4])


In [87]:
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [88]:
b

tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])

In [90]:
X = torch.arange(24).reshape(2, 3, 4)
print(X.shape)

y = X.transpose(1, 2)
print(y.shape)

z = X.permute(2, 0, 1)
print(z.shape)

torch.Size([2, 3, 4])
torch.Size([2, 4, 3])
torch.Size([4, 2, 3])


# tensor 연산 및 주요 함수

## element-wise 연산
- tensor와 상수 연산시, tensor와 tensor간 연산시 원소별로 처리한다.
- 행렬곱 연산을 제외하고 tensor간 연산시 피연산지 tensor간에 shape이 같아야 한다.
    - shape이 다를 경우 조건이 맞으면 broadcasting을 한 뒤에 연산한다. (size가 다른 축의 경우 한개의 피연산자 size가 1일 경우 복사하여 shape을 맞춘다.)
    

In [91]:
import torch

a = torch.arange(10).reshape(2,5)
b = torch.arange(10,20).reshape(2,5)
c = torch.arange(50, 55)

print(a)
print(b)
print(c)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([50, 51, 52, 53, 54])


In [92]:
print(a + 100)
print(a - 100)
print(a < 5)

tensor([[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109]])
tensor([[-100,  -99,  -98,  -97,  -96],
        [ -95,  -94,  -93,  -92,  -91]])
tensor([[ True,  True,  True,  True,  True],
        [False, False, False, False, False]])


In [94]:
print(a + b)
print(a == b)

tensor([[10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False]])


In [95]:
# broadcasting
# (2, 5) + (5, )  : [50, 51, 52, 53, 54]
# (2, 5) + (1, 5) : [[50, 51, 52, 53, 54]]
# (2, 5) + (2, 5) : [[50, 51, 52, 53, 54], [50, 51, 52, 53, 54]]
print(a + c)

tensor([[50, 52, 54, 56, 58],
        [55, 57, 59, 61, 63]])


## 주요 연산함수

In [97]:
torch.e

2.718281828459045

In [98]:
torch.pi

3.141592653589793

In [96]:
x=torch.arange(-4, 5).reshape(3,3)
print(x)
print(torch.abs(x))  # 절대값  
print(torch.sqrt(torch.abs(x)))  # 제곱근
print(torch.exp(x))  # torch.e**x
print(torch.log(torch.abs(x)))  # 밑이 e인 로그
print(torch.log(torch.exp(torch.tensor(1)))) # torch.log() 밑이 e인 로그계산
print(torch.log10(torch.tensor(10)))         # torch.log10() 밑이 10인 로그계산
print(torch.log2(torch.tensor(2)))           # torch.log2() 밑이 2인 로그계산
print("=====================")

tensor([[-4, -3, -2],
        [-1,  0,  1],
        [ 2,  3,  4]])
tensor([[4, 3, 2],
        [1, 0, 1],
        [2, 3, 4]])
tensor([[2.0000, 1.7321, 1.4142],
        [1.0000, 0.0000, 1.0000],
        [1.4142, 1.7321, 2.0000]])
tensor([[1.8316e-02, 4.9787e-02, 1.3534e-01],
        [3.6788e-01, 1.0000e+00, 2.7183e+00],
        [7.3891e+00, 2.0086e+01, 5.4598e+01]])
tensor([[1.3863, 1.0986, 0.6931],
        [0.0000,   -inf, 0.0000],
        [0.6931, 1.0986, 1.3863]])
tensor(1.0000)
tensor(1.)
tensor(1.)


In [99]:
y = x + torch.randn((3,3))
print(y)
print(torch.round(y)) # 반올림
print(torch.round(y, decimals=2)) # 소수점 둘째자리이하에서 반올림
print(torch.floor(y)) # 내림
print(torch.ceil(y)) # 올림

tensor([[-2.8828, -2.7839, -1.9083],
        [-2.5468, -1.3425,  1.8245],
        [ 0.9035,  2.9513,  3.5797]])
tensor([[-3., -3., -2.],
        [-3., -1.,  2.],
        [ 1.,  3.,  4.]])
tensor([[-2.8800, -2.7800, -1.9100],
        [-2.5500, -1.3400,  1.8200],
        [ 0.9000,  2.9500,  3.5800]])
tensor([[-3., -3., -2.],
        [-3., -2.,  1.],
        [ 0.,  2.,  3.]])
tensor([[-2., -2., -1.],
        [-2., -1.,  2.],
        [ 1.,  3.,  4.]])


### 행렬곱
- `@` 연산자 또는 `torch.matmul(tensor1, tensor2)` 함수 이용

In [1]:
import torch

In [2]:
x = torch.FloatTensor([[1, 2],
                       [3, 4],
                       [5, 6]
                      ])

y = torch.FloatTensor([[1, 2],
                       [1, 2],
                      ])
x.size(), y.shape

(torch.Size([3, 2]), torch.Size([2, 2]))

In [3]:
z1 = x @ y
z2 = torch.matmul(x, y)
print(z1.shape, z2.shape)
print(z1)
print(z2)

torch.Size([3, 2]) torch.Size([3, 2])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])


In [4]:
# Batch 행렬곱(Batch matrix muliplication) - bmm()
# x, y가 가지는 3개의 2차원 배열 간에 행렬곱을 처리한다.
import torch
x = torch.FloatTensor(3,4,2)
y = torch.FloatTensor(3,2,5)
z = torch.bmm(x, y)
z.shape


torch.Size([3, 4, 5])

## torch.nan, torch.inf
- nan: Not a Number, 주로 결측치를 표현한다.
- inf: infinit 무한. 
    - torch.inf: 양의 무한
    - -torch.inf: 음의 무한
- torch.isnan(tensor)
    - 원소별 결측치 확인
- torch.isinf(tensor)    
    - 원소별 inf 확인

In [5]:
print(torch.inf > 10, torch.inf < 10)
print(-torch.inf < 10, -torch.inf > 10)

True False
True False


In [8]:
print(torch.log(torch.tensor(-1))) # nan (계산이 안되는-없는 값)
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])).sum())  # nan 여부 확인
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))  # inf 여부 확인

tensor(nan)
tensor(1)
tensor([False, False, False, False,  True])


## 기술통계함수

In [9]:
X=torch.randn(3,4)
print(X)

tensor([[ 0.5087,  0.5001, -0.1052,  0.4312],
        [ 0.8424,  0.7798,  0.3952, -1.2119],
        [-1.0304,  0.9158, -1.0534,  0.8903]])


In [13]:
print(torch.sum(X), X.sum())  # 전체계산
print(torch.sum(X, dim=1))  # dim/axis 지정: 지정한 axis의 index가 다른 값끼리 계산
print(torch.sum(X, dim=1, keepdims=True))

tensor(1.8630) tensor(1.8630)
tensor([ 1.3349,  0.8056, -0.2776])
tensor([[ 1.3349],
        [ 0.8056],
        [-0.2776]])


In [14]:
print(torch.mean(X))
print(torch.mean(X, dim=1))
print(torch.mean(X, dim=1, keepdims=True))

tensor(0.1552)
tensor([ 0.3337,  0.2014, -0.0694])
tensor([[ 0.3337],
        [ 0.2014],
        [-0.0694]])


In [15]:
print(torch.std(X)) # standard deviation 표준 편차
print(torch.var(X)) # variance
print(torch.var(X, dim=0))
print(torch.var(X, dim=0, keepdims=True))

tensor(0.8069)
tensor(0.6511)
tensor([0.9979, 0.0449, 0.5413, 1.2216])
tensor([[0.9979, 0.0449, 0.5413, 1.2216]])


In [16]:
# apthem
print(X.sum(dim=1, keepdims=True))
print(X.mean(dim=1, keepdims=True))
print(X.std())

tensor([[ 1.3349],
        [ 0.8056],
        [-0.2776]])
tensor([[ 0.3337],
        [ 0.2014],
        [-0.0694]])
tensor(0.8069)


In [17]:
print(torch.max(X))
print(torch.max(X, dim=0))  # return_types.max 타입객체로 반환. max값과 max값의 index를 묶어서 반환
print(torch.max(X, dim=1))
print(torch.max(X, dim=1).values, torch.max(X, dim=1).indices, sep=" || ")
print(torch.max(X, dim=0, keepdims=True))  #keepdims=True : 차원(rank)를 유지
# print(torch.max(X, dim=1, keepdims=True))

tensor(0.9158)
torch.return_types.max(
values=tensor([0.8424, 0.9158, 0.3952, 0.8903]),
indices=tensor([1, 2, 1, 2]))
torch.return_types.max(
values=tensor([0.5087, 0.8424, 0.9158]),
indices=tensor([0, 0, 1]))
tensor([0.5087, 0.8424, 0.9158]) || tensor([0, 0, 1])
torch.return_types.max(
values=tensor([[0.8424, 0.9158, 0.3952, 0.8903]]),
indices=tensor([[1, 2, 1, 2]]))


In [18]:
print(torch.min(X))
print(torch.min(X, dim=0))
print(torch.min(X, dim=1))

tensor(-1.2119)
torch.return_types.min(
values=tensor([-1.0304,  0.5001, -1.0534, -1.2119]),
indices=tensor([2, 0, 2, 1]))
torch.return_types.min(
values=tensor([-0.1052, -1.2119, -1.0534]),
indices=tensor([2, 3, 2]))


In [19]:
X

tensor([[ 0.5087,  0.5001, -0.1052,  0.4312],
        [ 0.8424,  0.7798,  0.3952, -1.2119],
        [-1.0304,  0.9158, -1.0534,  0.8903]])

In [20]:
print(torch.argmax(X))
print(torch.argmax(X, dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(torch.argmax(X, dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

tensor(9)
tensor([1, 2, 1, 2])
tensor([0, 0, 1])


# autograd(자동미분)
- 자동 미분을 이용해 gradient를 계산하는 pytorch system.
- 딥러닝 모델에서 weight와 bias tensor들(Parameter)은 backpropagation(역전파)를 이용해 gradient를 구해서 loss가 줄어드는 방향으로 update를 하게된다.
- pytorch는 이런 미분 수행을 자동으로 처리해 준다.
    - gradient(기울기)를 구한다는 것은 미분을 한다는 것을 말한다.
- tensor가 미분 가능하려면 `requires_grad=True` 로 설정되 있어야 한다. (default: False)
    

In [21]:
x = torch.tensor([1.], requires_grad=True)
# x = torch.tensor([1.])
# x.requires_grad = True
print(x)
print(x.requires_grad)

tensor([1.], requires_grad=True)
True


In [22]:
y = x ** 2
print(y)
# 계산 결과를 담은 tensor인 y는 계산 결과와 grad_fn에 어떤 계산을 했는지 정보를 담고 있다. (PowBackward0)
# 이는 y 계산에 사용된 x가 requires_grad=True이기 때문이다.

tensor([1.], grad_fn=<PowBackward0>)


In [23]:
# 미분 - tensor.backward() 호출
y.backward()   # dy/dx  gradient 계산 후 결과를 x의 grad attribute에 저장한다.

In [24]:
x.grad
# 도함수: y` = 2x 이고 x가 1이었으므로 grad는 2

tensor([2.])

In [26]:
# requires_grad가 True로 설정되 있느 않은 경우
# x = torch.tensor([1.])
# y = x ** 2
# y.backward()

In [27]:
x = torch.tensor([1.], requires_grad=True)
y = x ** 2   # 미분: 2x
z = y * 10   # 미분: 10  ===> 2x * 10

z.backward()
print(x.grad)

tensor([20.])


In [28]:
## 편미분
x=torch.tensor([1.],requires_grad=True)
y=torch.tensor([1.],requires_grad=True)
z= 2*x**2 + y**2
print(z)
z.backward() 
print(x.grad)  #dz/dx
print(y.grad)  #dz/dy

tensor([3.], grad_fn=<AddBackward0>)
tensor([4.])
tensor([2.])


In [29]:
x=torch.tensor([1., 2., 3.] ,requires_grad=True)
y=torch.sum(x**2) # [x1**2 + x2**2 + x3**2]  
y.backward() #[dy/dx1, dy/dx2, dy/dx3] = [2x1, 2x2, 2x3]

print(y)
print(x.grad) # 스칼라를 벡터로 미분

tensor(14., grad_fn=<SumBackward0>)
tensor([2., 4., 6.])


## torch.no_grad() 
- no_grad() 구문에서 연산을 할 경우 requires_grad=True로 설정되었다 하더라도 gradient를 update하지 않는다.
- 딥러닝 모델 학습이 끝나고 평가할 때는 gradient를 계산할 필요가 없기 때문에 no_grad 구문을 사용한다.


In [30]:
x = torch.tensor(1.0, requires_grad = True)
print(x.requires_grad)

y = x**2

print(y.requires_grad)  # 연산이 결과 requires_grad도 True -> 그래야 미분이 가능하므로.
print(x.requires_grad)
print(y)

y.backward()
print(x.grad)



True
True
True
tensor(1., grad_fn=<PowBackward0>)
tensor(2.)


In [31]:
x = torch.tensor(1.0, requires_grad = True)
print(x.requires_grad)

with torch.no_grad():
    print(x.requires_grad)
    y = x**2  # torch.no_grad()로 인해서 도함수를 만들지 않는다.
    print(y.requires_grad)# 연산이 적용될 때 requires_grad가 False가 된다.
    print(y)
    
print(x.requires_grad)
# y.backward()  # y는 도함수를 만들지 않았기 때문에 Exception 발생


True
True
False
tensor(1.)
True


## gradient 값 초기화

In [ ]:
x = torch.tensor(1., requires_grad=True)
y = x**2
y.backward()
print("x의 gradient값:", x.grad )

In [ ]:
x

In [ ]:
z = x **2
z.backward()
print("x의 gradient값:", x.grad )


In [ ]:
x = torch.tensor(1., requires_grad=True)
y = x**2
y.backward()
x.grad

In [ ]:
# gradient초기화
x.grad = torch.tensor(0.)   # grad 속성값을 0으로 변경
z = x**2
z.backward()
x.grad